steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/stallion-routes', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/stallion-routes']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'stallion-routes'
      - '--image'
      - 'gcr.io/$PROJECT_ID/stallion-routes'
      - '--platform'
      - 'managed'
      - '--region'
      - 'europe-west2'
      - '--allow-unauthenticated'
      - '--add-cloudsql-instances'
      - 'stallionxpress:europe-west2:stallion-db'
      - '--set-env-vars'
      - 'DB_CONNECTION_NAME=stallionxpress:europe-west2:stallion-db,DB_USER=stallion_user,DB_PASS=stallionroutes123,DB_NAME=stallion_data'

images:
  - gcr.io/$PROJECT_ID/stallion-routes